class OrderStatus:
    PENDING = 'PENDING'
    FILLED = 'FILLED'
    CANCELLED = 'CANCELLED'
    SUBMITTED = 'SUBMITTED'
    REJECTED = 'REJECTED'
    EXPIRED = 'EXPIRED'
    COMPLETED = 'COMPLETED'


class OrderType:
    BUY_QUANTITY = 'BUY_QUANTITY'
    SELL_QUANTITY = 'SELL_QUANTITY'

    DIY_BUY = 'DIY_BUY'
    DIY_SELL = 'DIY_SELL'
    OPTIONS_BUY = 'OPTIONS_BUY'
    OPTIONS_SELL = 'OPTIONS_SELL'
    OPTIONS_MULTILEG = 'OPTIONS_MULTILEG'
    MANAGED_BUY = 'MANAGED_BUY'
    MANAGED_SELL = 'MANAGED_SELL'
    CRYPTO_BUY = 'CRYPTO_BUY'
    CRYPTO_SELL = 'CRYPTO_SELL'
    DIVIDEND = 'DIVIDEND'


class OrderSubType:
    LIMIT_ORDER = 'LIMIT_ORDER'
    MARKET_ORDER = 'MARKET_ORDER'
    STOP_ORDER = 'STOP_ORDER'
    STOP_LIMIT_ORDER = 'STOP_LIMIT_ORDER'
    FRACTIONAL_ORDER = 'FRACTIONAL_ORDER'
    DIVIDEND_REINVESTMENT = 'DIVIDEND_REINVESTMENT'


class ExecutionType:
    MARKET = 'MARKET'
    LIMIT = 'LIMIT'
    STOP = 'STOP'
    STOP_LIMIT = 'STOP_LIMIT'


class TimeInForce:
    DAY = 'DAY'
    GTC = 'GTC'
    GTD = 'GTD'
    IOC = 'IOC'
    FOK = 'FOK'
